version: '3.8'

services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops_fastapi_service
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: mlops_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - web_api
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: mlops_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    restart: always
