global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'mlops_fastapi_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web_api:8000', 'localhost:8000']
